* Information
** Image format
Images are apparently stored in the [[http://justsolve.archiveteam.org/wiki/Lightning_Strike][lightning strike
wavelet-compressed raster image format]]:
- archived [[https://web.archive.org/web/19970613234152/http://www.infinop.com/nhtml/lsinfo.shtml][web page from the company]]
- there is a [[https://patents.google.com/patent/WO1998040842A1][patent describing the approach]]
- archived [[https://web.archive.org/web/19990220121339/http://www.compsci.com/%7Echao/][homepage of one of the developers]] and [[https://web.archive.org/web/19990220160521/http://www.compsci.com/%7Echao/Publication/][her publication
  list]]; [[https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=3c08d5095a328950539dd8aa13cd11c5d05063f7][relevant paper]]: Hongyang Chao & Paul Fisher, An Approach of
  integer reversible wavelet transform for Lossless image
  compression, in /Advances in Computational Mathematics: Guangzhou,
  China – the proceedings of Guangzhou International Symposium on
  Computational Mathematics/, Aug. 11-15, 1997, Guangzhou, P.R.China
- There existed [[ftp://ftp.sunet.se/mirror/archive/ftp.sunet.se/pub/pc/windows/winsock-indstate/Windows95/WWW-Browsers/Plug-In/][a browser plugin to decode such images]].
  - There also existed a [[https://web.archive.org/web/19970613234343/http://www.infinop.com/nhtml/java/index.shtml][Java browser applet]] whose classes were
    available (after [[https://web.archive.org/web/19970613235015/http://www.infinop.com/nhtml/download.shtml][filling out a form]]), both directly usable
    (e.g., [[https://web.archive.org/web/19970613234343/http://www.infinop.com/nhtml/java/Lightning.class][Lightning.class]], not archived) and as archive from a
    [[compressed][download page]] (classes.tgz).
- there seem to be [[https://web.archive.org/web/19970613235015/http://www.infinop.com/nhtml/javafaq.shtml][different (incompatible) versions]]:
  #+begin_quote
  /I have tried to use some .cod images from my website inside the
  Java applet, and they do not display correctly. What could be
  wrong?/

  Most likely, they were compressed with an earlier version of
  Lightning Strike. The Java applet was designed for use with
  Lightning Strike 2.6 images, and for the sake of size and download
  time, was not made backward compatible. Try opening the images in
  the Lightning Strike 2.6 compressor and then resaving them in the
  new format.
  #+end_quote

** Coordinate format
- an older [[https://groups.google.com/g/de.org.ccc/c/xlaNafyxmrM/m/hXZj7J5ksc8J][usenet discussion on how to decode the geo coordinates]]
  - did we consider [[https://en.wikipedia.org/wiki/SK-42_reference_system][SK-42]] and derivatives?

* Next Steps

- [ ] Visualise the structure of dsatnord.mp, that is, where are city
  names and coordinates, where are the tiles, etc. Maybe that helps to
  find the index for the tiles.
- [ ] testing the Netscape plugin:
  - [ ] install it in a VM together with an older version of Firefox
  - [ ] test it with a [[http://justsolve.archiveteam.org/wiki/Lightning_Strike][sample image]]
  - [ ] write one tile into a file and try to open it
- [ ] test [[https://en.wikipedia.org/wiki/SK-42_reference_system][SK-42]] and derivatives

* Files
- ~dsatnord.mp~ - data for D-Sat 1 CD 1
- ~NPLS32.DLL~ - browser plugin for Netscape/Firefox
